# generic 
arch: "resnet18" # prefer densenet/WideResNet (ref: bag of tricks adv. training)

# dataset
dataset: "styleganC_cifar10"
data_dir: "/data/data_vvikash/fall20/stylegan_ada/cifra10/"
mode: "org"
size: 32
normalize: False
workers: 4

# optimization
epochs: 25
batch_size: 128
batch_size_syn: 128
lr: 0.01
weight_decay: 0.0005
momentum: 0.9

# adversarial examples
epsilon: 0.031
num_steps: 4
step_size: 0.015
clip_min: 0.
clip_max: 1.
distance: "linf"
beta: 6.0

# data subset
training_images: 250000
num_classes: 2
classes: [1, 9]