# generic 
arch: "resnet18" # prefer densenet/WideResNet (ref: bag of tricks adv. training)
activation: "ReLU"
swa: True
tau: 0.999

# dataset
dataset: "cifar10"
data_dir: "/data/data_vvikash/datasets"
mode: "org"
num_classes: 10
size: 32
normalize: False
workers: 4

# optimization
epochs: 100
batch_size: 256
batch_size_syn: 256
lr: 0.01
weight_decay: 0.0005
momentum: 0.9

# adversarial examples
epsilon: 0.031
num_steps: 10
step_size: 0.0078
clip_min: 0.
clip_max: 1.
distance: "linf"
beta: 6.0
